### ISSUE TITLE
Support tutor >= 17.0.0 (quince)

### ISSUE THREAD

**Issue by snglth** [openedx/openedx-k8s-harmony#61] opened 2024-01-30 10:04 UTC
Currently the [version constraint](https://github.com/openedx/openedx-k8s-harmony/blob/2cb4c67b754c22d9a47411cb8c1ae68ff4b74270/tutor-contrib-harmony-plugin/setup.py#L43) in setup.py won't allow you to use harmony in tutor 17 projects. Is there anything that holds us from supporting tutor 17?

**Comment by jfavellar90** [comment] 2024-02-20 15:53
@snglth sorry for the late answer and thanks for reporting the issue. We are in the process of adding the proper support to the Harmony Tutor plugin. In the next few days, we'll proceed with the proper versioning of the plugin so it supports the latest Tutor version. We'll let you know once this is done

**Comment by jfavellar90** [comment] 2024-03-05 16:54
@snglth This is still WIP. There's a [draft PR](https://github.com/openedx/openedx-k8s-harmony/pull/63) with the basic changes for Quince support, however, there are a couple of issues that need to be fixed before releasing the Quince-compatible version. We'll keep you posted about the progress on this task.

**Comment by gabor-boros** [comment] 2024-03-22 03:14
@jfavellar90 Could you please elaborate on what are the issues you are facing with? I'd be happy to help as I got blocked on this too.

**Comment by gabor-boros** [comment] 2024-03-27 05:51
@jfavellar90 or @felipemontoya do you have any insights?

**Comment by jfavellar90** [comment] 2024-04-16 15:30
Sorry @gabor-boros @farhaanbukhsh, my schedule was hectic in the last 2 weeks. I did a basic test of the plugin in Quince and from the configuration side of things, it's working OK as already confirmed in the [PR](https://github.com/openedx/openedx-k8s-harmony/pull/63) (I don't remember exactly the reason of my previous failure). What's missing is testing the commands added by the plugin and check they're behaving as expected.

**Comment by gabor-boros** [comment] 2024-04-22 09:06
The related PRs #63 and #70 are merged. The latest version of the plugin will support Quince.

**Closed by gabor-boros** 2024-04-22 09:06 UTC

**Comment by farhaanbukhsh** [comment] 2024-04-30 06:37
@gabor-boros  Thank you for taking care of this.
